-- lab02 https://github.com/MicrosoftLearning/QueryingT-SQL/blob/master/Labs/Lab02.pdf

-- challenge 1
-- 1
SELECT DISTINCT CITY, STATEPROVINCE
 FROM SALESLT.ADDRESS;
-- 2
SELECT TOP 10 PERCENT NAME, WEIGHT
FROM SALESLT.PRODUCT
ORDER BY WEIGHT DESC;
-- 3
SELECT NAME, WEIGHT
FROM SALESLT.PRODUCT
ORDER BY WEIGHT DESC
OFFSET 10 ROWS FETCH NEXT 100 ROWS ONLY;
-- challenge 2
SELECT * FROM SALESLT.PRODUCT;
-- 1
SELECT NAME, COLOR, SIZE
FROM SALESLT.PRODUCT
WHERE PRODUCTMODELID = 1;
-- 2
SELECT NAME, PRODUCTNUMBER
FROM SALESLT.PRODUCT
WHERE COLOR IN ('BLACK', 'RED', 'WHITE') AND SIZE IN ('S', 'M');
-- 3
SELECT PRODUCTNUMBER, NAME, LISTPRICE
FROM SALESLT.PRODUCT 
WHERE PRODUCTNUMBER LIKE 'BK-%';
-- 4
SELECT PRODUCTNUMBER, NAME, LISTPRICE
FROM SALESLT.PRODUCT
WHERE PRODUCTNUMBER NOT LIKE 'BK-R%' 
AND  PRODUCTNUMBER LIKE 'BK-%' 
AND  PRODUCTNUMBER LIKE '%-[0-9][0-9]';

-- OU

SELECT ProductNumber, Name, ListPrice
FROM SalesLT.Product 
WHERE ProductNumber LIKE 'BK-[^R]%-[0-9][0-9]';