-- lab 03 https://github.com/MicrosoftLearning/QueryingT-SQL/blob/master/Labs/Lab03.pdf
-- challenge 01
-- 1
SELECT * FROM SALESLT.CUSTOMER;
SELECT * FROM SALESLT.SALESORDERHEADER;
SELECT C.COMPANYNAME, S.SALESORDERID, S.TOTALDUE
FROM SALESLT.SALESORDERHEADER AS S
JOIN SALESLT.CUSTOMER AS C
ON S.CUSTOMERID  = C.CUSTOMERID;
-- 2
SELECT * FROM SALESLT.ADDRESS;
SELECT * FROM SALESLT.CUSTOMERADDRESS;
SELECT * FROM SALESLT.CUSTOMER;
SELECT * FROM SALESLT.SALESORDERHEADER;

SELECT * FROM SALESLT.SALESORDERHEADER AS S
WHERE S.CUSTOMERID IN (29503, 29545, 29559, 29772, 29816, 29861, 29883, 29897, 29954, 30018); 


UPDATE SALESLT.SALESORDERHEADER
SET CUSTOMERID = 29559
WHERE CUSTOMERID = 30033;


SELECT C.CustomerID, C.COMPANYNAME, S.SALESORDERID, S.TOTALDUE, A.ADDRESSLINE1 + ISNULL(A.ADDRESSLINE2, ''), A.CITY, A.STATEPROVINCE, A.POSTALCODE, A.COUNTRYREGION 
FROM SALESLT.SALESORDERHEADER AS S
JOIN SALESLT.CUSTOMER AS C
ON S.CUSTOMERID  = C.CUSTOMERID
JOIN SALESLT.CUSTOMERADDRESS AS CA
ON CA.CUSTOMERID = C.CUSTOMERID and CA.AddressType = 'Main Office'
JOIN SALESLT.ADDRESS AS A
ON CA.ADDRESSID = A.AddressID
WHERE CA.AddressType = 'Main Office'
ORDER BY C.CUSTOMERID;



-- challenge 02
-- 1
SELECT * FROM SALESLT.CUSTOMER;
SELECT * FROM SALESLT.SALESORDERHEADER;

SELECT C.FIRSTNAME + ' ' + C.LASTNAME AS FULLNAME, S.SALESORDERID, S.TOTALDUE
FROM SALESLT.CUSTOMER AS C
LEFT JOIN SALESLT.SALESORDERHEADER AS S
ON S.CUSTOMERID = C.CUSTOMERID
ORDER BY S.CUSTOMERID DESC;
-- 2
SELECT * FROM SALESLT.CUSTOMER;
SELECT * FROM SALESLT.CUSTOMERADDRESS;

SELECT C.CUSTOMERID, C.COMPANYNAME, C.FIRSTNAME + ' ' + C.LASTNAME AS FULLNAME , C.PHONE
FROM SALESLT.CUSTOMER AS C
EXCEPT
SELECT C.CUSTOMERID, C.COMPANYNAME, C.FIRSTNAME + ' ' + C.LASTNAME AS FULLNAME , C.PHONE
FROM SALESLT.CUSTOMER AS C
JOIN SALESLT.CUSTOMERADDRESS AS A
ON A.CUSTOMERID = C.CUSTOMERID;

 -- ou

SELECT c.CompanyName, c.FirstName, c.LastName, c.Phone
FROM SalesLT.Customer AS c
LEFT JOIN SalesLT.CustomerAddress AS ca
ON c.CustomerID = ca.CustomerID
WHERE ca.AddressID IS NULL;


-- 3
SELECT * FROM SALESLT.CUSTOMER;
SELECT * FROM SALESLT.PRODUCT;
SELECT * FROM SALESLT.SALESORDERHEADER;
SELECT * FROM SALESLT.SALESORDERDETAIL;

SELECT c.CustomerID, p.ProductID
FROM SalesLT.Customer AS c
FULL JOIN SalesLT.SalesOrderHeader AS oh
ON c.CustomerID = oh.CustomerID
FULL JOIN SalesLT.SalesOrderDetail AS od
ON od.SalesOrderID = oh.SalesOrderID
FULL JOIN SalesLT.Product AS p
ON p.ProductID = od.ProductID
WHERE oh.SalesOrderID IS NULL
ORDER BY ProductID, CustomerID;
