-- LAB 07 https://github.com/MicrosoftLearning/QueryingT-SQL/blob/master/Labs/Lab07.pdf
-- challenge 1
-- 1

SELECT * FROM SALESLT.vProductModelCatalogDescription;
SELECT * FROM SALESLT.PRODUCT;
SELECT * FROM SALESLT.PRODUCTMODEL;
SELECT P.PRODUCTID, P.NAME AS ProductName, V.NAME as ModelName, V.SUMMARY
FROM SALESLT.vProductModelCatalogDescription AS V
JOIN SALESLT.PRODUCT AS P
ON P.PRODUCTMODELID = V.PRODUCTMODELID
ORDER BY P.PRODUCTID;


-- 2
DECLARE @colors AS TABLE (Color nvarchar(15));

INSERT INTO @COLORS
SELECT DISTINCT P.COLOR 
FROM SALESLT.PRODUCT AS P;

SELECT * FROM @COLORS;
-- 3

sp_helptext 'dbo.ufnGetAllCategories'

SELECT P.PRODUCTID, P.NAME, CA.PARENTPRODUCTCATEGORYNAME, CA.PRODUCTCATEGORYNAME
FROM SALESLT.PRODUCT AS P
JOIN dbo.ufnGetAllCategories() AS CA
ON P.ProductCategoryID  = CA.ProductCategoryID
ORDER BY CA.PARENTPRODUCTCATEGORYNAME, CA.PRODUCTCATEGORYNAME, P.NAME;

-- challenge
-- 1
SELECT * FROM SALESLT.CUSTOMER;
SELECT * FROM SALESLT.SALESORDERHEADER;

WITH CustomerSales(CompanyContact, SalesAmount)
AS
(

	SELECT C.COMPANYNAME + ' (' + C.FIRSTNAME + ' ' + C.LASTNAME + ')', S.TOTALDUE
	FROM SALESLT.SALESORDERHEADER AS S
	JOIN SALESLT.CUSTOMER AS C
	ON C.CustomerID = S.CustomerID)
SELECT CompanyContact, SUM(SalesAmount) AS Revenue
FROM CustomerSales
GROUP BY CompanyContact
ORDER BY CompanyContact;

SELECT COMPANYCONTACT, SUM(SALESAMOUNT) AS REVENUE
FROM (

	SELECT C.COMPANYNAME + ' (' + C.FIRSTNAME + ' ' + C.LASTNAME + ')' AS CompanyContact,
	 S.TOTALDUE AS SalesAmount
	FROM SALESLT.SALESORDERHEADER AS S
	JOIN SALESLT.CUSTOMER AS C
	ON C.CustomerID = S.CustomerID) as CUSTOMERSALES
GROUP BY COMPANYCONTACT
ORDER BY COMPANYCONTACT;